pull_request_title: 'chore(i18n-crowdin): new crowdin translation 🌐'
commit_message: 'chore(i18n-crowdin): new translations for %original_file_name% (%language%)'
append_commit_message: false

files:
  - source: /apps/foxxie/src/Core/languages/en-US/**/*.json
    translation: /apps/foxxie/src/Core/languages/%locale%/**/%original_file_name%
