import { envParseString } from '@skyra/env-utilities';
import { EnvKeys } from '#lib/types';
import { Translate } from '#root/Bot/Resources/Intl/Util/Translate';

import { ReadonlyGuildData } from '../Types/Guilds.js';

export type DefaultGuildData = Omit<ReadonlyGuildData, 'id'>;

export class Constants {
	public static GetDefaultGuildSettings() {
		Constants.CachedDefaultGuildSettings ??= Object.assign(Object.create(null), {
			birthdayChannel: null,
			birthdayRole: null,
			channelsIgnoreAll: [],
			channelsIgnoreMessageDelete: [],
			channelsIgnoreMessageEdit: [],
			channelsIgnoreReactionAdd: [],
			channelsLogsChannelCreate: null,
			channelsLogsChannelDelete: null,
			channelsLogsChannelUpdate: null,
			channelsLogsEmojiCreate: null,
			channelsLogsEmojiDelete: null,
			channelsLogsEmojiUpdate: null,
			channelsLogsImage: null,
			channelsLogsMemberAdd: null,
			channelsLogsMemberNicknameUpdate: null,
			channelsLogsMemberRemove: null,
			channelsLogsMemberRolesUpdate: null,
			channelsLogsMemberUsernameUpdate: null,
			channelsLogsMessageDelete: null,
			channelsLogsMessageDeleteNsfw: null,
			channelsLogsMessageUpdate: null,
			channelsLogsMessageUpdateNsfw: null,
			channelsLogsModeration: null,
			channelsLogsPrune: null,
			channelsLogsReaction: null,
			channelsLogsRoleCreate: null,
			channelsLogsRoleDelete: null,
			channelsLogsRoleUpdate: null,
			channelsLogsServerUpdate: null,
			channelsLogsVoiceActivity: null,
			channelsMediaOnly: [],
			disabledChannels: [],
			disabledCommands: [],
			disabledCommandsChannels: [],
			disableNaturalPrefix: false,
			disboardChannel: null,
			disboardEmbed: null,
			disboardMessage: null,
			eventsBanAdd: false,
			eventsBanRemove: false,
			eventsKick: true,
			eventsMuteAdd: true,
			eventsMuteRemove: true,
			highlights: [],
			language: Translate.SupportedLanguages.EnglishUnitedStates,
			levelingMessagesEnabled: true,
			levelingRoles: [],
			messageCount: 0,
			messagesAutoDeleteIgnoredAll: false,
			messagesAutoDeleteIgnoredChannels: [],
			messagesAutoDeleteIgnoredCommands: [],
			messagesAutoDeleteIgnoredRoles: [],
			messagesIgnoreChannels: [],
			messagesModerationAutoDelete: false,
			messagesModerationDm: false,
			messagesModerationMessageDisplay: true,
			messagesModerationReasonDisplay: true,
			messagesModeratorNameDisplay: true,
			permissionsRoles: [],
			permissionsUsers: [],
			prefix: envParseString(EnvKeys.ClientPrefix),
			reactionRoles: [],
			rolesAdmin: [],
			rolesInitialBots: [],
			rolesInitialHumans: [],
			rolesModerator: [],
			rolesMuted: null,
			rolesPersist: [],
			rolesPersistEnabled: true,
			rolesRestrictedAttachment: null,
			rolesRestrictedEmbed: null,
			rolesRestrictedEmoji: null,
			rolesRestrictedReaction: null,
			rolesRestrictedVoice: null,
			selfmodAttachmentsEnabled: false,
			selfmodAttachmentsHardAction: 0,
			selfmodAttachmentsHardActionDuration: null,
			selfmodAttachmentsIgnoredChannels: [],
			selfmodAttachmentsIgnoredRoles: [],
			selfmodAttachmentsSoftAction: 0,
			selfmodAttachmentsThresholdDuration: 60000,
			selfmodAttachmentsThresholdMaximum: 10,
			selfmodCapitalsEnabled: false,
			selfmodCapitalsHardAction: 0,
			selfmodCapitalsHardActionDuration: null,
			selfmodCapitalsIgnoredChannels: [],
			selfmodCapitalsIgnoredRoles: [],
			selfmodCapitalsMaximum: 50,
			selfmodCapitalsMinimum: 15,
			selfmodCapitalsSoftAction: 0,
			selfmodCapitalsThresholdDuration: 60000,
			selfmodCapitalsThresholdMaximum: 10,
			selfmodFilterEnabled: false,
			selfmodFilterHardAction: 0,
			selfmodFilterHardActionDuration: null,
			selfmodFilterIgnoredChannels: [],
			selfmodFilterIgnoredRoles: [],
			selfmodFilterRaw: [],
			selfmodFilterSoftAction: 0,
			selfmodFilterThresholdDuration: 60000,
			selfmodFilterThresholdMaximum: 10,
			selfmodIgnoredChannels: [],
			selfmodInvitesEnabled: false,
			selfmodInvitesHardAction: 0,
			selfmodInvitesHardActionDuration: null,
			selfmodInvitesIgnoredChannels: [],
			selfmodInvitesIgnoredCodes: [],
			selfmodInvitesIgnoredGuilds: [],
			selfmodInvitesIgnoredRoles: [],
			selfmodInvitesSoftAction: 0,
			selfmodInvitesThresholdDuration: 60000,
			selfmodInvitesThresholdMaximum: 10,
			selfmodLinksAllowed: [],
			selfmodLinksEnabled: false,
			selfmodLinksHardAction: 0,
			selfmodLinksHardActionDuration: null,
			selfmodLinksIgnoredChannels: [],
			selfmodLinksIgnoredRoles: [],
			selfmodLinksSoftAction: 0,
			selfmodLinksThresholdDuration: 60000,
			selfmodLinksThresholdMaximum: 10,
			selfmodMessagesEnabled: false,
			selfmodMessagesHardAction: 0,
			selfmodMessagesHardActionDuration: null,
			selfmodMessagesIgnoredChannels: [],
			selfmodMessagesIgnoredRoles: [],
			selfmodMessagesMaximum: 5,
			selfmodMessagesQueueSize: 50,
			selfmodMessagesSoftAction: 0,
			selfmodMessagesThresholdDuration: 60000,
			selfmodMessagesThresholdMaximum: 10,
			selfmodNewlinesEnabled: false,
			selfmodNewlinesHardAction: 0,
			selfmodNewlinesHardActionDuration: null,
			selfmodNewlinesIgnoredChannels: [],
			selfmodNewlinesIgnoredRoles: [],
			selfmodNewlinesMaximum: 20,
			selfmodNewlinesSoftAction: 0,
			selfmodNewlinesThresholdDuration: 60000,
			selfmodNewlinesThresholdMaximum: 10,
			selfmodReactionsAllowed: [],
			selfmodReactionsBlocked: [],
			selfmodReactionsEnabled: false,
			selfmodReactionsHardAction: 0,
			selfmodReactionsHardActionDuration: null,
			selfmodReactionsIgnoredChannels: [],
			selfmodReactionsIgnoredRoles: [],
			selfmodReactionsMaximum: 10,
			selfmodReactionsSoftAction: 0,
			selfmodReactionsThresholdDuration: 60000,
			selfmodReactionsThresholdMaximum: 10,
			starboardChannelId: null,
			starboardEmojis: ['⭐️', '✨'],
			starboardIgnoredChannels: [],
			starboardMinimum: 3,
			starboardSelfStar: true,
			suggestionsAutoThread: true,
			suggestionsButtons: false,
			suggestionsChannel: null,
			suggestionsEmbed: true,
			suggestionsUpdateHistory: true,
			tags: [],
			words: []
		} as const satisfies DefaultGuildData);

		return Constants.CachedDefaultGuildSettings;
	}

	private static CachedDefaultGuildSettings: DefaultGuildData | null = null;
}
