-- CreateTable
CREATE TABLE "schedule" (
    "id" SERIAL NOT NULL,
    "taskId" VARCHAR NOT NULL,
    "time" TIMESTAMP(6) NOT NULL,
    "recurring" VARCHAR,
    "catchUp" BOOLEAN NOT NULL DEFAULT true,
    "data" JSONB NOT NULL,

    CONSTRAINT "schedule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "moderation" (
    "caseId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(6),
    "duration" BIGINT,
    "extraData" JSON,
    "guildId" VARCHAR(19) NOT NULL,
    "moderatorId" VARCHAR(19) NOT NULL,
    "reason" VARCHAR(2000),
    "imageUrl" VARCHAR(2000),
    "refrenceId" SMALLINT,
    "userId" VARCHAR(19),
    "channelId" VARCHAR(19),
    "logChannelId" VARCHAR(19),
    "logMessageId" VARCHAR(19),
    "type" SMALLINT NOT NULL,
    "metadata" SMALLINT NOT NULL DEFAULT 0,

    CONSTRAINT "moderation_pkey" PRIMARY KEY ("caseId","guildId")
);

-- CreateTable
CREATE TABLE "starboard" (
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "userId" VARCHAR(19),
    "messageId" VARCHAR(19) NOT NULL,
    "channelId" VARCHAR(19),
    "guildId" VARCHAR(19) NOT NULL,
    "starMessageId" VARCHAR(19),
    "stars" SMALLINT NOT NULL DEFAULT 0,

    CONSTRAINT "starboard_pkey" PRIMARY KEY ("messageId","guildId")
);

-- CreateTable
CREATE TABLE "guilds" (
    "id" VARCHAR(19) NOT NULL,
    "prefix" VARCHAR(10) NOT NULL,
    "language" VARCHAR NOT NULL DEFAULT 'en-US',
    "disable-natural-prefix" BOOLEAN NOT NULL DEFAULT false,
    "disabled-commands" VARCHAR(32)[] DEFAULT (ARRAY[]::character varying[])::character varying(32)[],
    "permissions.users" JSONB NOT NULL DEFAULT '[]',
    "permissions.roles" JSONB NOT NULL DEFAULT '[]',
    "channels.media-only" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "channels.logs.moderation" VARCHAR(19),
    "channels.logs.image" VARCHAR(19),
    "channels.logs.member-add" VARCHAR(19),
    "channels.logs.member-remove" VARCHAR(19),
    "channels.logs.member-nickname-update" VARCHAR(19),
    "channels.logs.member-username-update" VARCHAR(19),
    "channels.logs.member-roles-update" VARCHAR(19),
    "channels.logs.message-delete" VARCHAR(19),
    "channels.logs.message-delete-nsfw" VARCHAR(19),
    "channels.logs.message-update" VARCHAR(19),
    "channels.logs.message-update-nsfw" VARCHAR(19),
    "channels.logs.prune" VARCHAR(19),
    "channels.logs.reaction" VARCHAR(19),
    "channels.logs.role-create" VARCHAR(19),
    "channels.logs.role-update" VARCHAR(19),
    "channels.logs.role-delete" VARCHAR(19),
    "channels.logs.channel-create" VARCHAR(19),
    "channels.logs.channel-update" VARCHAR(19),
    "channels.logs.channel-delete" VARCHAR(19),
    "channels.logs.emoji-create" VARCHAR(19),
    "channels.logs.emoji-update" VARCHAR(19),
    "channels.logs.emoji-delete" VARCHAR(19),
    "channels.logs.server-update" VARCHAR(19),
    "channels.logs.voice-activity" VARCHAR(19),
    "channels.ignore.all" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "channels.ignore.message-edit" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "channels.ignore.message-delete" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "channels.ignore.reaction-add" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "disabled-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "disabled-commands-channels" JSONB NOT NULL DEFAULT '[]',
    "events.ban-add" BOOLEAN NOT NULL DEFAULT true,
    "events.ban-remove" BOOLEAN NOT NULL DEFAULT true,
    "events.kick" BOOLEAN NOT NULL DEFAULT true,
    "events.mute-add" BOOLEAN NOT NULL DEFAULT true,
    "events.mute-remove" BOOLEAN NOT NULL DEFAULT true,
    "message-count" SMALLINT NOT NULL DEFAULT 0,
    "messages.ignore-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "messages.moderation-dm" BOOLEAN NOT NULL DEFAULT false,
    "messages.moderation-reason-display" BOOLEAN NOT NULL DEFAULT true,
    "messages.moderation-message-display" BOOLEAN NOT NULL DEFAULT true,
    "messages.moderation-auto-delete" BOOLEAN NOT NULL DEFAULT false,
    "messages.moderator-name-display" BOOLEAN NOT NULL DEFAULT true,
    "messages.auto-delete.ignored-all" BOOLEAN NOT NULL DEFAULT false,
    "messages.auto-delete.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "messages.auto-delete.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "messages.auto-delete.ignored-commands" VARCHAR(32)[] DEFAULT (ARRAY[]::character varying[])::character varying(32)[],
    "roles.persist" JSONB NOT NULL DEFAULT '[]',
    "roles.persist-enabled" BOOLEAN NOT NULL DEFAULT true,
    "reaction-roles" JSONB NOT NULL DEFAULT '[]',
    "roles.admin" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "roles.initial-humans" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "roles.initial-bots" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "roles.moderator" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "roles.muted" VARCHAR(19),
    "roles.restricted-reaction" VARCHAR(19),
    "roles.restricted-embed" VARCHAR(19),
    "roles.restricted-emoji" VARCHAR(19),
    "roles.restricted-attachment" VARCHAR(19),
    "roles.restricted-voice" VARCHAR(19),
    "selfmod.attachments.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.attachments.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.attachments.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.attachments.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.attachments.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.attachments.hard-action-duration" BIGINT,
    "selfmod.attachments.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.attachments.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.capitals.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.capitals.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.capitals.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.capitals.minimum" SMALLINT NOT NULL DEFAULT 15,
    "selfmod.capitals.maximum" SMALLINT NOT NULL DEFAULT 50,
    "selfmod.capitals.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.capitals.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.capitals.hard-action-duration" BIGINT,
    "selfmod.capitals.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.capitals.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.links.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.links.allowed" VARCHAR(128)[] DEFAULT (ARRAY[]::character varying[])::character varying(128)[],
    "selfmod.links.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.links.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.links.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.links.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.links.hard-action-duration" BIGINT,
    "selfmod.links.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.links.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.messages.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.messages.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.messages.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.messages.maximum" SMALLINT NOT NULL DEFAULT 5,
    "selfmod.messages.queue-size" SMALLINT NOT NULL DEFAULT 50,
    "selfmod.messages.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.messages.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.messages.hard-action-duration" BIGINT,
    "selfmod.messages.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.messages.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.newlines.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.newlines.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.newlines.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.newlines.maximum" SMALLINT NOT NULL DEFAULT 20,
    "selfmod.newlines.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.newlines.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.newlines.hard-action-duration" BIGINT,
    "selfmod.newlines.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.newlines.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.invites.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.invites.ignored-codes" VARCHAR[] DEFAULT ARRAY[]::VARCHAR[],
    "selfmod.invites.ignored-guilds" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.invites.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.invites.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.invites.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.invites.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.invites.hard-action-duration" BIGINT,
    "selfmod.invites.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.invites.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.filter.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.filter.raw" VARCHAR(32)[] DEFAULT (ARRAY[]::character varying[])::character varying(32)[],
    "selfmod.filter.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.filter.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.filter.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.filter.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.filter.hard-action-duration" BIGINT,
    "selfmod.filter.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.filter.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.reactions.enabled" BOOLEAN NOT NULL DEFAULT false,
    "selfmod.reactions.ignored-roles" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.reactions.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "selfmod.reactions.maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.reactions.allowed" VARCHAR(128)[] DEFAULT (ARRAY[]::character varying[])::character varying(128)[],
    "selfmod.reactions.blocked" VARCHAR(128)[] DEFAULT (ARRAY[]::character varying[])::character varying(128)[],
    "selfmod.reactions.soft-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.reactions.hard-action" SMALLINT NOT NULL DEFAULT 0,
    "selfmod.reactions.hard-action-duration" BIGINT,
    "selfmod.reactions.threshold-maximum" SMALLINT NOT NULL DEFAULT 10,
    "selfmod.reactions.threshold-duration" INTEGER NOT NULL DEFAULT 60000,
    "selfmod.ignored-channels" VARCHAR(19)[] DEFAULT (ARRAY[]::character varying[])::character varying(19)[],
    "starboard.channel_id" VARCHAR(19),
    "starboard.emojis" VARCHAR(128)[] DEFAULT (ARRAY[]::character varying[])::character varying(128)[],
    "starboard.minimum" SMALLINT NOT NULL DEFAULT 3,
    "starboard.self-star" BOOLEAN NOT NULL DEFAULT true,
    "tags" JSONB NOT NULL DEFAULT '[]',
    "words" JSONB NOT NULL DEFAULT '[]',

    CONSTRAINT "guilds_pkey" PRIMARY KEY ("id")
);

